/**
 * Expo config plugin: raise Gradle/Kotlin daemon JVM memory limits.
 *
 * The default gradle.properties generated by prebuild does not allocate
 * enough Metaspace for the Kotlin compiler daemon (used by KSP annotation
 * processing, e.g. expo-updates) when building on memory-constrained CI
 * runners such as GitHub's standard 2-core/7GB ubuntu-latest. Without this,
 * the build fails with:
 *
 *   e: [ksp] java.lang.OutOfMemoryError: Metaspace
 *
 * This did not surface in local builds on developer machines with more RAM.
 * Increasing org.gradle.jvmargs and kotlin.daemon.jvmargs headroom fixes it
 * without needing a larger (paid) runner.
 */

const { withGradleProperties } = require('@expo/config-plugins');

const GRADLE_PROPERTIES = {
  'org.gradle.jvmargs': '-Xmx4096m -XX:MaxMetaspaceSize=1024m',
  'kotlin.daemon.jvmargs': '-Xmx2048m -XX:MaxMetaspaceSize=1024m',
};

/** @param {import('@expo/config-plugins').ExpoConfig} config */
function withGradleJvmMemory(config) {
  return withGradleProperties(config, (config) => {
    for (const [key, value] of Object.entries(GRADLE_PROPERTIES)) {
      const existingIndex = config.modResults.findIndex(
        (item) => item.type === 'property' && item.key === key
      );

      if (existingIndex >= 0) {
        config.modResults[existingIndex].value = value;
      } else {
        config.modResults.push({ type: 'property', key, value });
      }
    }

    return config;
  });
}

module.exports = withGradleJvmMemory;
