-- ADR: docs/adr/0017-casual-stopwatch-shared-sessions.md
--
-- Casual Stopwatch surface: sessions, participants, events, and security-definer RPCs.
-- Creator must be a signed-in Supabase auth user (owner_id = auth.uid()::text).
-- Joiners remain frictionless (no account required).
-- All anon access goes through security-definer RPCs — no direct table grants.

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

create table casual_sessions (
  id              uuid primary key default gen_random_uuid(),
  owner_id        text not null,                 -- auth.uid()::text, matches events.owner_id pattern
  name            text not null check (char_length(name) between 1 and 80),
  code            text unique not null,           -- 6-char, generated by create_casual_session RPC
  status          text not null default 'waiting'
                    check (status in ('waiting','running','stopped')),
  created_at      timestamptz not null default now(),
  expires_at      timestamptz not null,           -- default now() + interval '4 hours'
  participant_cap smallint not null default 10,
  t0_server       timestamptz                     -- null until first start event
);

-- RLS: owner can read/update own sessions; anon can read by code via join_casual_session RPC
alter table casual_sessions enable row level security;
create policy "owner can manage own sessions"
  on casual_sessions for all
  using (owner_id = auth.uid()::text);
-- No anon select — all anon access goes through security-definer RPCs

create index on casual_sessions (owner_id);
create index on casual_sessions (expires_at);

-- ---------------------------------------------------------------------------

create table casual_session_participants (
  id           uuid primary key default gen_random_uuid(),
  session_id   uuid not null references casual_sessions(id) on delete cascade,
  display_name text not null check (char_length(display_name) between 1 and 30),
  client_id    uuid not null,               -- idempotency: re-join returns existing row
  joined_at    timestamptz not null default now(),
  is_owner     boolean not null default false,
  unique (session_id, client_id)
);
alter table casual_session_participants enable row level security;
-- No direct grants — access via RPCs only

create index on casual_session_participants (session_id, client_id);

-- ---------------------------------------------------------------------------

create table casual_session_events (
  id                   uuid primary key,    -- CLIENT-generated idempotency key
  session_id           uuid not null references casual_sessions(id) on delete cascade,
  actor_participant_id uuid not null references casual_session_participants(id),
  event_type           text not null check (event_type in ('start','lap','stop','reset')),
  client_recorded_at   timestamptz not null,
  server_received_at   timestamptz not null default now(),
  sequence             bigint not null generated always as identity
);
alter table casual_session_events enable row level security;
-- No direct grants — access via RPCs only

create index on casual_session_events (session_id, sequence);

-- ---------------------------------------------------------------------------
-- Helper: code generation (34-char alphabet, no O/I/0/1)
-- ---------------------------------------------------------------------------

create or replace function generate_session_code() returns text language plpgsql as $$
declare
  alphabet text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'; -- 34 chars, no O/I/0/1
  code text := '';
  i int;
begin
  for i in 1..6 loop
    code := code || substr(alphabet, (random()*33)::int + 1, 1);
  end loop;
  return code;
end;
$$;

-- ---------------------------------------------------------------------------
-- RPC: create_casual_session — requires authenticated caller
-- ---------------------------------------------------------------------------

create or replace function create_casual_session(p_name text, p_display_name text)
returns json language plpgsql security definer as $$
declare
  v_owner_id     text := auth.uid()::text;
  v_code         text;
  v_session_id   uuid;
  v_participant_id uuid;
  attempts       int := 0;
begin
  if v_owner_id is null then
    raise exception 'UNAUTHENTICATED';
  end if;
  if char_length(p_name) < 1 or char_length(p_name) > 80 then
    raise exception 'INVALID_NAME';
  end if;
  if char_length(p_display_name) < 1 or char_length(p_display_name) > 30 then
    raise exception 'INVALID_DISPLAY_NAME';
  end if;
  -- unique code with retry
  loop
    v_code := generate_session_code();
    begin
      insert into casual_sessions (owner_id, name, code, expires_at)
        values (v_owner_id, p_name, v_code, now() + interval '4 hours')
        returning id into v_session_id;
      exit;
    exception when unique_violation then
      attempts := attempts + 1;
      if attempts > 10 then raise exception 'CODE_GENERATION_FAILED'; end if;
    end;
  end loop;
  -- owner participant
  insert into casual_session_participants (session_id, display_name, client_id, is_owner)
    values (v_session_id, p_display_name, gen_random_uuid(), true)
    returning id into v_participant_id;
  return json_build_object(
    'session_id',     v_session_id,
    'participant_id', v_participant_id,
    'code',           v_code
  );
end;
$$;

-- ---------------------------------------------------------------------------
-- RPC: join_casual_session — anon ok
-- ---------------------------------------------------------------------------

create or replace function join_casual_session(p_code text, p_display_name text, p_client_id uuid)
returns json language plpgsql security definer as $$
declare
  v_session        casual_sessions;
  v_participant_id uuid;
begin
  select * into v_session from casual_sessions where code = p_code;
  if not found or v_session.expires_at < now() or v_session.status = 'stopped' then
    raise exception 'SESSION_NOT_JOINABLE';
  end if;
  if char_length(p_display_name) < 1 or char_length(p_display_name) > 30 then
    raise exception 'INVALID_DISPLAY_NAME';
  end if;
  -- idempotent re-join
  select id into v_participant_id from casual_session_participants
    where session_id = v_session.id and client_id = p_client_id;
  if found then
    return json_build_object(
      'session_id',     v_session.id,
      'participant_id', v_participant_id,
      'session_name',   v_session.name
    );
  end if;
  -- cap check
  if (select count(*) from casual_session_participants where session_id = v_session.id) >= v_session.participant_cap then
    raise exception 'SESSION_FULL';
  end if;
  insert into casual_session_participants (session_id, display_name, client_id)
    values (v_session.id, p_display_name, p_client_id)
    returning id into v_participant_id;
  return json_build_object(
    'session_id',     v_session.id,
    'participant_id', v_participant_id,
    'session_name',   v_session.name
  );
end;
$$;

-- ---------------------------------------------------------------------------
-- RPC: record_session_event — anon ok (participant_id acts as bearer token)
-- ---------------------------------------------------------------------------

create or replace function record_session_event(
  p_session_id         uuid,
  p_participant_id     uuid,
  p_event_type         text,
  p_client_recorded_at timestamptz,
  p_client_event_id    uuid
) returns json language plpgsql security definer as $$
declare
  v_session     casual_sessions;
  v_participant casual_session_participants;
begin
  -- verify participant belongs to session
  select * into v_participant from casual_session_participants
    where id = p_participant_id and session_id = p_session_id;
  if not found then raise exception 'UNAUTHORIZED'; end if;
  select * into v_session from casual_sessions where id = p_session_id;
  -- concurrency rules
  if p_event_type = 'start' then
    if v_session.status = 'running' then raise exception 'SESSION_ALREADY_RUNNING'; end if;
    update casual_sessions set status = 'running', t0_server = coalesce(t0_server, now())
      where id = p_session_id;
  elsif p_event_type = 'lap' then
    if v_session.status != 'running' then raise exception 'SESSION_NOT_RUNNING'; end if;
  elsif p_event_type = 'stop' then
    if v_session.status != 'running' then return null; end if; -- no-op
    update casual_sessions set status = 'stopped' where id = p_session_id;
  elsif p_event_type = 'reset' then
    if not v_participant.is_owner then raise exception 'UNAUTHORIZED'; end if;
    if v_session.status != 'stopped' then raise exception 'SESSION_NOT_STOPPED'; end if;
    update casual_sessions set status = 'waiting', t0_server = null where id = p_session_id;
    delete from casual_session_events where session_id = p_session_id;
    return null;
  end if;
  -- upsert event (idempotent)
  insert into casual_session_events (id, session_id, actor_participant_id, event_type, client_recorded_at)
    values (p_client_event_id, p_session_id, p_participant_id, p_event_type, p_client_recorded_at)
    on conflict (id) do nothing;
  return row_to_json((select e from casual_session_events e where e.id = p_client_event_id));
end;
$$;

-- ---------------------------------------------------------------------------
-- RPC: get_session_state — catch-up on reconnect (anon ok, participant_id bearer)
-- ---------------------------------------------------------------------------

create or replace function get_session_state(p_session_id uuid, p_participant_id uuid)
returns json language plpgsql security definer as $$
declare
  v_participant casual_session_participants;
begin
  select * into v_participant from casual_session_participants
    where id = p_participant_id and session_id = p_session_id;
  if not found then raise exception 'UNAUTHORIZED'; end if;
  return json_build_object(
    'session',      (select row_to_json(s) from casual_sessions s where s.id = p_session_id),
    'participants', (select json_agg(p) from casual_session_participants p where p.session_id = p_session_id),
    'events',       (select json_agg(e order by e.sequence) from casual_session_events e where e.session_id = p_session_id)
  );
end;
$$;

-- ---------------------------------------------------------------------------
-- Realtime publication
-- Channel name convention: stopwatch:<code>
-- ---------------------------------------------------------------------------

alter publication supabase_realtime add table casual_session_events;
alter publication supabase_realtime add table casual_session_participants;
